
ga:
  num_generations: 8 # ~500 images in general
  num_parents_mating: 10
  sol_per_pop: 20
  mutation_percent_genes: 10
  init_range_low: -0.1
  init_range_high: 0.1

fitness:
  perturbation_weight: 0.01
  pixel_constraint_weight: 0.5
  max_perturbation_magnitude: 85

model:
  model_type: "googlenet"
  batch_size: 64

visualization:
  visualize: True
  visualize_every: 1