ga:
  num_generations: 64 # ~500 images in general (for 8 gen)
  num_parents_mating: 10
  sol_per_pop: 50
  init_range_low: -0.5
  init_range_high: 0.5
  parent_selection_type: "tournament"
  keep_elitism: 0
  keep_parents: 0

crossover:
  crossover_type: "uniform"
  p_crossover_init: 0.9
  p_crossover_end: 0.4
  pixel_cleaning_probability: 0.1

mutation:
  p_mutation_init: 0.6
  p_mutation_end: 0.2
  # p_m: 0.3
  p_flip: 0.005

fitness:
  # epsilon: 100
  epsilon_init: 85
  epsilon_end: 35
  penalty_factor: 0.2

model:
  model_type: "googlenet"
  batch_size: 64

visualization:
  visualize: True
  visualize_every: 16