
ga:
  num_generations: 100
  num_parents_mating: 10
  sol_per_pop: 20
  mutation_percent_genes: 10
  init_range_low: -0.1
  init_range_high: 0.1

model:
  model_type: "googlenet"

fitness:
  perturbation_weight: 0.01